# synced from @nextcloud/android-config
name: Auto approve
on:
  pull_request_target:
    branches:
      - master
      - main

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3.2.1 # v3.1.0
        if: ${{ contains(github.event.pull_request.labels.*.name, 'sync') && github.actor == 'nextcloud-android-bot' }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
